# -*- coding: utf-8 -*-
"""the4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TN2z57Ir0dujxhtwUuGpP2-ncetjh_G7
"""

#Muhammed Orhun Gale

product_list = []
date_list = []
year_list = []

info = input("Products and their purchasing dates: ")
info_list = info.split(",")

price = input("Prices of the products: ")
price_list = price.split(",")

for element in info_list:
  temp_list = element.split("_")
  product_list.append(temp_list[0])
  date_list.append(temp_list[1])
  temp_list.clear()

for y in date_list:
  plist = y.split(".")
  year_list.append(plist[2])


check = True

while check == True:
  interval = input("Starting Year-Ending Year: ")
  if len(interval) != 9:
    print("Years were not entered in correct format.")
  else:
    year1,year2 = interval.split("-")
    if year1.isdigit() == False or year2.isdigit() == False:
      print("Years were not entered in correct format.")
    else:
      dif = int(year2) - int(year1)
      if dif >= 0:
        check = False
      else:
        print("Years were not entered in correct format.")



prod_name = input("Product Name: ")

while prod_name not in product_list:
  print("The customer did not buy this product.")
  prod_name = input("Product Name: ")

price = 0

for lol in info_list:
  if prod_name in lol:
    x = info_list.index(lol)
    if year1 <= year_list[x] <= year2:
      price += float(price_list[x])

if prod_name in product_list:
  print("Customer spent "+str(price)+" for "+prod_name+ " in years "+str(interval)+".")